version: '3.4'

services:
  feedbackplatform:
    image: ${DOCKER_REGISTRY-}feedbackplatform
    build:
      context: .
      dockerfile: FeedbackPlatform/Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - 5164:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 8215:8215
   
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://peabody28.com:8215
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always